import type { Request, Response, NextFunction } from 'express';
import { AppError } from '../utils/AppError.js'; import { sendSuccess } from '../utils/response.js'; import { HttpStatus } from '../types/api.types.js';
import * as service from '../services/currency.service.js'; import { createCurrencySchema, updateCurrencySchema } from '../validators/currency.validator.js';
export async function listCurrencies(_req: Request, res: Response, next: NextFunction): Promise<void> { try { sendSuccess(res, 'Currencies retrieved', await service.getActiveCurrencies()); } catch (error) { next(error); } }
export async function listAdminCurrencies(_req: Request, res: Response, next: NextFunction): Promise<void> { try { sendSuccess(res, 'Currencies retrieved', await service.getManagedCurrencies()); } catch (error) { next(error); } }
export async function createAdminCurrency(req: Request, res: Response, next: NextFunction): Promise<void> { try { const parsed = createCurrencySchema.safeParse(req.body); if (!parsed.success) throw AppError.badRequest(parsed.error.issues[0]?.message ?? 'Invalid request body'); sendSuccess(res, 'Currency created', await service.createManagedCurrency(parsed.data), HttpStatus.CREATED); } catch (error) { next(error); } }
export async function updateAdminCurrency(req: Request, res: Response, next: NextFunction): Promise<void> { try { const parsed = updateCurrencySchema.safeParse(req.body); if (!parsed.success) throw AppError.badRequest(parsed.error.issues[0]?.message ?? 'Invalid request body'); sendSuccess(res, 'Currency updated', await service.updateManagedCurrency(req.params['id'] as string, parsed.data)); } catch (error) { next(error); } }
export async function setAdminDefaultCurrency(req: Request, res: Response, next: NextFunction): Promise<void> { try { sendSuccess(res, 'Default currency updated', await service.makeDefaultCurrency(req.params['id'] as string)); } catch (error) { next(error); } }
export async function deleteAdminCurrency(req: Request, res: Response, next: NextFunction): Promise<void> { try { await service.removeManagedCurrency(req.params['id'] as string); sendSuccess(res, 'Currency deactivated'); } catch (error) { next(error); } }
